#路由 AI
[[routes]]
rules=[
    # > AI
    # > ChatGPT [openai]
    "geosite:openai",
    # > Copilot
    "domain:api.trongrid.io",
    "domain:www.bing.com",
    "domain:bing.com",
    "domain:sydney.bing.com",
    "domain:sydney.vcanbb.chat",
    "domain:bingai.nothingnessvoid.tech",
    # > Claude [anthropic]
    "geosite:anthropic",
    # > Gemini [google deepmind]
    "geosite:google-deepmind",
]


[[routes.Outs]]
listen=""
type="xxx"
server="xxx"
port=12345
password="xxx"
cipher="xxx"
