#路由 AI
[[routes]]
rules=[
    # > AI
    # > ChatGPT
    "geosite:openai",
    "domain:chatgpt.com",
    "domain:openai.com",
    "domain:cdn.auth0.com",
    "domain:azureedge.net",
    "domain:sentry.io",
    "domain:azurefd.net",
    "domain:intercomcdn.com",
    "domain:intercom.io",
    "domain:google-analytics.com",
    "domain:identrust.com",
    "domain:challenges.cloudflare.com",
    "domain:ai.com",
    # > Copilot
    "domain:api.trongrid.io",
    "domain:www.bing.com",
    "domain:bing.com",
    "domain:sydney.bing.com",
    "domain:sydney.vcanbb.chat",
    "domain:bingai.nothingnessvoid.tech",
    # > Claude
    "domain:claude.ai",
    "domain:www.claude.ai",
    # > Gemini
    "domain:gemini.google.com",
    "domain:proactivebackend-pa.googleapis.com",
]

[[routes.Outs]]
listen=""
type="xxx"
server="xxx"
port=12345
password="xxx"
cipher="xxx"
