#路由 跨国
[[routes]]
rules=[
    #Main
    # > Netflix
    "geosite:netflix",
    "domain:netflix.ca", 
    "domain:netflix.com",
    "domain:netflix.net",
    "domain:netflixinvestor.com",
    "domain:netflixtechblog.com",
    "domain:nflxext.com",
    "domain:nflximg.com",
    "domain:nflximg.net",
    "domain:nflxsearch.net",
    "domain:nflxso.net",
    "domain:nflxvideo.net",
    "domain:netflixdnstest1.com",
    "domain:netflixdnstest2.com",
    "domain:netflixdnstest3.com",
    "domain:netflixdnstest4.com",
    "domain:netflixdnstest5.com",
    "domain:netflixdnstest6.com",
    "domain:netflixdnstest7.com",
    "domain:netflixdnstest8.com",
    "domain:netflixdnstest9.com",
    "domain:netflixdnstest10.com",
    # > Tiktok
    "domain:tiktok.com",
    "domain:www.tiktok.com",
    # > TVB
    "domain:tvb.com",
    "domain:tvb.com.au",
    "domain:tvbanywhere.com",
    "domain:tvbanywhere.com.sg",
    "domain:tvbc.com.cn",
    "domain:tvbeventpower.com.hk",
    "domain:tvbusa.com",
    "domain:tvbweekly.com",
    "domain:tvmedia.net.au",
    "domain:videos-f.jwpsrv.com",
    # > Dazn
    "domain:dazn-api.com",
    "domain:dazn.com",
    "domain:dazndn.com",
    "domain:indazn.com",
    "domain:indaznlab.com",
    # > Amazon Prime Video
    "domain:d1v5ir2lpwr8os.cloudfront.net",
    "domain:d22qjgkvxw22r6.cloudfront.net",
    "domain:d25xi40x97liuc.cloudfront.net",
    "domain:d27xxe7juh1us6.cloudfront.net",
    "domain:dmqdd6hw24ucf.cloudfront.net",
    "domain:atv-ext-eu.amazon.com",
    "domain:atv-ext-fe.amazon.com",
    "domain:atv-ext.amazon.com",
    "domain:atv-ps-eu.amazon.co.uk",
    "domain:atv-ps-eu.amazon.com",
    "domain:atv-ps-fe.amazon.co.jp",
    "domain:atv-ps-fe.amazon.com",
    "domain:atv-ps.amazon.com",
    "domain:aiv-cdn.net",
    "domain:aiv-delivery.net",
    "domain:amazonprimevideo.cn",
    "domain:amazonprimevideo.com.cn",
    "domain:amazonprimevideos.com",
    "domain:amazonvideo.cc",
    "domain:amazonvideo.com",
    "domain:avodmp4s3ww-a.akamaihd.net",
    "domain:fls-na.amazon.com",
    "domain:pv-cdn.net",
    "domain:video.a2z.com",
    "domain:media-amazon.com",
    "domain:prime-video.com",
    "domain:primevideo.com",
    "domain:primevideo.org",
    "domain:primevideo.tv",
    # > Disney
    "domain:disney.asia",
    "domain:disney.be",
    "domain:disney.bg",
    "domain:disney.ca",
    "domain:disney.ch",
    "domain:disney.co.il",
    "domain:disney.co.jp",
    "domain:disney.co.kr",
    "domain:disney.co.th",
    "domain:disney.co.uk",
    "domain:disney.co.za",
    "domain:disney.com",
    "domain:disney.com.au",
    "domain:disney.com.br",
    "domain:disney.com.hk",
    "domain:disney.com.tw",
    "domain:disney.cz",
    "domain:disney.de",
    "domain:disney.dk",
    "domain:disney.es",
    "domain:disney.fi",
    "domain:disney.fr",
    "domain:disney.gr",
    "domain:disney.hu",
    "domain:disney.id",
    "domain:disney.in",
    "domain:disney.io",
    "domain:disney.it",
    "domain:disney.my",
    "domain:disney.nl",
    "domain:disney.no",
    "domain:disney.ph",
    "domain:disney.pl",
    "domain:disney.pt",
    "domain:disney.ro",
    "domain:disney.ru",
    "domain:disney.se",
    "domain:disney.sg",
    "domain:adventuresbydisney.com",
    "domain:disney-asia.com",
    "domain:disney-discount.com",
    "domain:disney-plus.net",
    "domain:disney-studio.com",
    "domain:disney-studio.net",
    "domain:disneyadsales.com",
    "domain:disneyarena.com",
    "domain:disneyaulani.com",
    "domain:disneybaby.com",
    "domain:disneycareers.com",
    "domain:disneychannelonstage.com",
    "domain:disneychannelroadtrip.com",
    "domain:disneycruisebrasil.com",
    "domain:disneyenconcert.com",
    "domain:disneyiejobs.com",
    "domain:disneyinflight.com",
    "domain:disneyinternational.com",
    "domain:disneyinternationalhd.com",
    "domain:disneyjunior.com",
    "domain:disneyjuniortreataday.com",
    "domain:disneylatino.com",
    "domain:disneymagicmoments.co.il",
    "domain:disneymagicmoments.co.uk",
    "domain:disneymagicmoments.co.za",
    "domain:disneymagicmoments.de",
    "domain:disneymagicmoments.es",
    "domain:disneymagicmoments.fr",
    "domain:disneymagicmoments.gen.tr",
    "domain:disneymagicmoments.gr",
    "domain:disneymagicmoments.it",
    "domain:disneymagicmoments.pl",
    "domain:disneymagicmomentsme.com",
    "domain:disneyme.com",
    "domain:disneymeetingsandevents.com",
    "domain:disneymovieinsiders.com",
    "domain:disneymusicpromotion.com",
    "domain:disneynewseries.com",
    "domain:disneynow.com",
    "domain:disneypeoplesurveys.com",
    "domain:disneyplus.com",
    "domain:disneyredirects.com",
    "domain:disneysrivieraresort.com",
    "domain:disneystore.com",
    "domain:disneystreaming.com",
    "domain:disneysubscription.com",
    "domain:disneytickets.co.uk",
    "domain:disneyturkiye.com.tr",
    "domain:disneytvajobs.com",
    "domain:disneyworld-go.com",
    "domain:go-disneyworldgo.com",
    "domain:go.com",
    "domain:mickey.tv",
    "domain:shopdisney.com",
    "domain:shops-disney.com",
    "domain:sorcerersarena.com",
    "domain:spaindisney.com",
    "domain:streamingdisney.net",
    "domain:watchdisneyfe.com",
    "domain:disney.api.edge.bamgrid.com",
    # > Spotify
    "domain:spotify.com",
    "domain:www.spotify.com",
    # > Hbo MAX
    "domain:max.com",
    "domain:go.com",
    "domain:maxgo.com",
    "domain:hbo.com",
    "domain:hbonow.com",
    "domain:hbogo.com",
    "domain:hbomax.com",
    "domain:hbomaxcdn.com",
    "domain:forthethrone.com",
    "domain:cinemax.com",
    "domain:discomax.com",
    "domain:conviva.com",
    "domain:akamaihd.net",
    "domain:boltdns.net",
    "domain:comhbo.com",
    "domain:brightline.tv",
    "domain:litix.io",
    "domain:now-ashare.com",
    "domain:now-tv.com",
    "domain:now.com.hk",
    "domain:nowe.com",
    "domain:nowe.hk",
    "domain:hbogo.co.th",
    "domain:hbogo.eu",
    "domain:hboasia.com",
    "domain:hbogoasia.com",
    "domain:hbogoasia.hk",
    "domain:hbogoasia.id",
    "domain:hbogoasia.ph",
    "domain:hbogoasia.sg",
    "domain:hbogoasia.tw",
    "domain:hboasia1-i.akamaihd.net",
    "domain:hboasia2-i.akamaihd.net",
    "domain:hboasia3-i.akamaihd.net",
    "domain:hboasia4-i.akamaihd.net",
    "domain:hboasia5-i.akamaihd.net",
    "domain:hboasialive.akamaized.net",
    "domain:hbogoprod-vod.akamaized.net",
    "domain:wmff.warnermediacdn.com",
]

[[routes.Outs]]
listen=""
type="xxx"
server="xxx"
port=12345
password="xxx"
cipher="xxx"
