#路由 劫持
[[routes]]
rules=[
    "domain:cp.cloudflare.com",
    "domain:gstatic.com",
    "domain:i.ytimg.com",
    "domain:nmcheck.gnome.org",
    "domain:detectportal.firefox.com",
    "domain:captive.apple.com",
    "domain:captive.v2ex.co",
    "domain:latency-test.skk.moe",
    "domain:connectivitycheck.android.com",
]

[[routes.Outs]]
type="direct"

#路由 Emby
[[routes]]
rules=[
    # 来源: surge/emby/emby-direct.list
    # 倒闭Direct
    "domain:lax.sexemby.com",
    "domain:cn2.sexemby.com",
    "domain:direct.sexemby.com",
    "full:cdn.jiedaibao.gs",
    "full:cdn2.jiedaibao.gs",
    "domain:wangdai.us",
    # Tank
    "domain:tiangou.xyz",
    # 熊猫
    "domain:pdatv.cc",
    # 蘑菇
    "domain:yeahfast.com",
    # LongEmby
    "domain:longemby.com",
    "domain:longemby.top",

    "full:vip.nanflix.net",
    "full:embymv.top",
    "full:mcdn.mobaiemby.site",
    "full:jp.fc.newneeship.com",
    "full:cloud.s1.xxzi.top",
    "full:jelly.s1.xxzi.top",
    "domain:oemby.com",
    "domain:191616.xyz",
    "domain:127255.best",
    "domain:pdtvs.de",
    "domain:xn--fhq389femyc1d.com",
    "domain:luminoustrace.xyz",
    "domain:115cdn.de",
    "domain:echoflix.vip",
    "domain:lyrebirdemby.online",
    "domain:uhdnow.com",
    "domain:uhdgo.com",
    "domain:525778.xyz",
    "domain:455676.xyz",
    "domain:xhyonline.com",
    "domain:8880080.xyz",
    "domain:4348663.xyz",
    "domain:cinebay.net",
    "domain:goglobe.pro",

    # 来源: surge/emby/emby-proxy.list
    # 倒闭Porn
    "domain:cancanbi.com",
    "full:db.jiedaibao.gs",
    # 倒闭主线路
    "domain:cdn.sexemby.com",
    # ZDZ PRE
    "domain:emby.to",
    # JMS PRE
    "domain:ikuramoe.com",
    "domain:st8.one",
    # 叔服
    "domain:mcjoker.xyz",
    # 墨白
    "domain:mobaiemby.site",
    # GUGU
    "domain:guguemby.site",
    "domain:gugu.media",
    # 喜鹊
    "domain:223789.xyz",
    "domain:023168.xyz",
    # PronEmby
    "domain:ii00.cc",
    # 奥德赛
    "domain:odysseyplus.site",
    # 新船
    "domain:newneeship.com",
    # shrek
    "domain:shrekmedia.org",

    "full:orionx-global.sandwichcat.de",
    "full:us.nanflix.net",
    "domain:pandtv.de",
    "domain:ntrrr.top",
    "domain:biliblili.uk",
    "domain:pilipiliultra.com",
    "domain:chilledmelon.com",
    "domain:viclub.top",
    "domain:785858.xyz",
    "domain:3msky.com",
    "domain:ash.yt",
    "domain:emby.wtf",
    "domain:yezi.my",
    "domain:violet.run",
    "domain:onyra.cc",
    "domain:onyra.uk",
    "domain:saturdayvideo.top",
    "domain:285286.xyz",
    "domain:10101.io",
    "domain:domob.org",
    "domain:alphatvapp.top",
    "domain:term.wtf",
    "domain:emby.my",
    "domain:vban.xyz",
    "domain:3767483.xyz",
    "domain:000115.xyz",
    "domain:bangumi.ca",
    "domain:younoyes.com",
    "domain:niceduck.lol",
    "domain:114514.quest",
    "domain:anisaga.tv",
    "domain:qtecrab.com",
    "domain:605305.xyz",
    "ip:83.147.61.152/32",
    "ip:104.160.170.190/32",
    "domain:cn2gias.uk",
    "domain:jmsooo.com",
    "magpie",
    "domain:emby.aca.best",
    "domain:porn.aca.best",
    "domain:cc.ccemby.tk",
    "domain:line.emby.men",
    "domain:mius.uk",
    "domain:emby.flowercloud",
    "domain:emby.immtel.com",
    "domain:ju.dog",
    "ip:202.61.255.248/32",
    "domain:charontv.com",
    "domain:misakaf.org",
    "domain:push-kr.cfprefer3.xyz",
    "domain:mjjemby.org",
    "domain:emby.maying.club",
    "domain:ntrrr.am.sb",
    "domain:emby.nexitally.com",
    "domain:direct.nebula-emby.com",
    "domain:pilipiliultra.top",
    "domain:pornemby.club",
    "domain:poloemby.xyz",
    "domain:pololine.ml",
    "domain:embyplus.club",
    "domain:emby.cjpc.cc",
    "domain:emby.prprcloud.com",
    "domain:emby.plusmedia.site",
    "domain:emby-cf.plusmedia.site",
    "domain:emby-sg.plusmedia.site",
    "domain:stream.synn.cc",
    "full:notnetflix.cos.cat",
    "domain:123456.al",
    "domain:embyclub.com",
    "domain:emby.xeton.dev",
    "domain:jellyfin.xeton.dev",
    "domain:movie.xeton.dev",
    "domain:servers.xeton.dev",
    "domain:emby.ytoo.li",
    "domain:emby.mdss.cloud",
    "domain:embyserver.ga",
    "domain:emby.nyancat.net",
    "domain:emby.otakudrive.life",
    "domain:emby2.otakudrive.life",
    "domain:emby.run",
    "domain:emby.p-p.men",
    "domain:emby.aiyowei.ml",
    "domain:gfwemby.org",
    "domain:loseremby.org",
    "domain:speedx.one",
    "domain:embymv.tk",
    "domain:bddup.com",
    "domain:emby.cl",
    "domain:emby.ml",
    "domain:nivod4.tv",
    "domain:newpppp.com",
    "domain:freetz.top",
    "domain:newwan.top",
    "domain:shuipo.lol",
    "domain:dicarerhome.com",
    "domain:emby77.cf",
    "domain:embyplus.org",
    "ip:188.172.228.49/32",
    "domain:embytv.cf",
    "domain:zox.show",
    "domain:acemby.org",
    "domain:bili.rip",
    "domain:misty.ltd",
    "domain:ednovas.org",
    "domain:deja-vu.beauty",
    "domain:studyfun.live",
    "domain:gtlx.org",
    "domain:9191001.xyz",
    "domain:carlos.trade",
    "domain:agon.cf",
    "domain:imetyou.top",
    "domain:goodisp.org",
    "domain:emby77.org",
    "domain:emby.eu.org",
    "domain:wiri.tk",
    "domain:zi0.icu",
    "domain:emby.kim",
    "domain:4545.cf",
    "domain:ggtt.cf",
    "domain:mulgore.net",
    "domain:happyav.eu.org",
    "domain:emby.pro",
    "domain:xiaoyi.one",
    "domain:embymv.me",
    "domain:infinityfly.top",
    "domain:lucasmedia.top",
    "domain:nvidia.rip",
    "domain:20120714.xyz",
    "domain:gugumedia.link",
    "domain:starcat.eu.org",
    "domain:catlinks.co.uk",
    "domain:emby.ws",
    "domain:ohhhh.org",
    "domain:xmsl.org",
    "domain:9521732.xyz",
    "domain:jmsuper.com",
]

[[routes.Outs]]
type="direct"

#CDN
[[routes]]
rules=[
    # 来源: blackmatrix7 GameDownload
    "full:assets1.xboxlive.com",
    "full:assets2.xboxlive.com",
    "full:blizzard.gcdn.cloudn.co.kr",
    "full:blzddist1-a.akamaihd.net",
    "full:blzddistkr1-a.akamaihd.net",
    "full:client.hikarifield.co.jp",
    "full:content.cdp.bethesda.net",
    "full:download.cdp.bethesda.net",
    "full:download.dm.origin.com",
    "full:download.epicgames.com",
    "full:download.hikarifield.co.jp",
    "full:download2.epicgames.com",
    "full:download3.epicgames.com",
    "full:download4.epicgames.com",
    "full:edge.steam-dns.top.comcast.net",
    "full:epicgames-download1.akamaized.net",
    "full:eu.cdn.blizzard.com",
    "full:fastly-download.epicgames.com",
    "full:gamedownloads-rockstargames-com.akamaized.net",
    "full:gog-cdn-lumen.secure2.footprint.net",
    "full:kr.cdn.blizzard.com",
    "full:level3.blizzard.com",
    "full:origin-a.akamaihd.net",
    "full:packagespc.xboxlive.com",
    "full:ssl-lvlt.cdn.ea.com",
    "full:steam.eca.qtlglb.com",
    "full:steam.naeu.qtlglb.com",
    "full:steam.ru.qtlglb.com",
    "full:steampipe-kr.akamaized.net",
    "full:steampipe-partner.akamaized.net",
    "full:steampipe.akamaized.net",
    "full:steamusercontent-a.akamaihd.net",
    "full:uplaypc-s-ubisoft.cdn.ubionline.com.cn",
    "full:us.cdn.blizzard.com",
    "full:xvcf1.xboxlive.com",
    "full:xvcf2.xboxlive.com",
    "domain:cdn.ubi.com",
    "domain:dyn.riotcdn.net",
    "domain:steamcontent.com",

    # 来源: blackmatrix7 GameDownloadCN
    "full:assets1.xboxlive.cn",
    "full:assets2.xboxlive.cn",
    "full:cdn-ali.content.steamchina.com",
    "full:cdn-qc.content.steamchina.com",
    "full:cdn-ws.content.steamchina.com",
    "full:dl.delivery.mp.microsoft.com",
    "full:dl.steam.clngaa.com",
    "full:epicgames-download1-1251447533.file.myqcloud.com",
    "full:st.dl.bscstorage.net",
    "full:st.dl.eccdnx.com",
    "full:steampipe.steamcontent.tnkjmec.com",
    "full:tlu.dl.delivery.mp.microsoft.com",
    "full:trts.baishancdnx.cn",
    "full:xz.pphimalayanrt.com",
    "domain:pdl.wow.battlenet.com.cn",

    # 补充: blackmatrix7 SteamCN 中明确的下载/静态节点
    "full:dl.steam.ksyna.com",
    "full:st.dl.pinyuncloud.com",
    "full:steampowered.com.8686c.com",
    "full:steamstatic.com.8686c.com",
    "domain:cm.steampowered.com",
    "domain:steamserver.net",
    "domain:steamusercontent.com",
]

[[routes.Outs]]
type="direct"

#路由 Download
[[routes]]
rules=[
    # YouTube
    "geosite:youtube",
    # Game Download
    "geosite:category-game-platforms-download",
    # Android Download
    "geosite:category-android-app-download",
]

[[routes.Outs]]
type="direct"
